### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by St0ner1995** [roccomuso/alveare#1]
Hello,

when i try to start the package, i get this error

```
/usr/local/lib/node_modules/alveare/cli.js:3
const {start} = require('./lib/index')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

have i done something wrong?

fresh install of nodejs on ubuntu 16.04.3 LTS

**Comment by roccomuso** [comment]
@St0ner1995 What version of Node.js? `node -v`

**Comment by St0ner1995** [comment]
v4.2.6

**Comment by roccomuso** [comment]
That version of node doesn't support js [destructuring](http://node.green/#ES2015-syntax-destructuring--assignment). Update to version `v6.4.0` or above.

```javascript
// destructuring example
const {start} = require('./lib/index')
// is equals to:
const start = require('./lib/index').start
```
